/* 
* Copyright 2005-2008, Foundations of Success, Bethesda, Maryland 
* (on behalf of the Conservation Measures Partnership, "CMP") and 
* Beneficent Technology, Inc. ("Benetech"), Palo Alto, California. 
*/ 
package org.conservationmeasures.eam.questions;

public class HabitatAssociationQuestion extends StaticChoiceQuestion
{
	public HabitatAssociationQuestion()
	{
		super(getHabitatAssociationChoices());
	}

	static ChoiceItem[] getHabitatAssociationChoices()
	{
		return new ChoiceItem[] {
				new ChoiceItem("1", "1. Forest"),
				new ChoiceItem("1.1", "1.1. Forest - Boreal"), 
				new ChoiceItem("1.2", "1.2. Forest - Subarctic"), 
				new ChoiceItem("1.3", "1.3. Forest - Subantarctic"), 
				new ChoiceItem("1.4", "1.4. Forest - Temperate"), 
				new ChoiceItem("1.5", "1.5. Forest - Subtropical/Tropical Dry"), 
				new ChoiceItem("1.6", "1.6. Forest - Subtropical/Tropical Moist Lowland"), 
				new ChoiceItem("1.7", "1.7. Forest - Subtropical/Tropical Mangrove Vegetation Above High Tide Level"), 
				new ChoiceItem("1.8", "1.8. Forest - Subtropical/Tropical Swamp"), 
				new ChoiceItem("1.9", "1.9. Forest - Subtropical/Tropical Moist Montane"), 
				new ChoiceItem("2", "2. Savanna"),
				new ChoiceItem("2.1", "2.1. Savanna - Dry Savanna"), 
				new ChoiceItem("2.2", "2.2. Savanna - Moist Savana"), 
				new ChoiceItem("3", "3. Shrubland"),
				new ChoiceItem("3.1", "3.1. Shrubland - Subarctic"), 
				new ChoiceItem("3.2", "3.2. Shrubland - Subantarctic"), 
				new ChoiceItem("3.3", "3.3. Shrubland - Boreal"), 
				new ChoiceItem("3.4", "3.4. Shrubland - Temperate"), 
				new ChoiceItem("3.5", "3.5. Shrubland - Subtropical/Tropical Dry"), 
				new ChoiceItem("3.6", "3.6. Shrubland - Subtropical/Tropical Moist"), 
				new ChoiceItem("3.7", "3.7. Shrubland - Subtropical/Tropical High Altitude"), 
				new ChoiceItem("3.8", "3.8. Shrubland - Mediterranean-type Shrubby Vegetation"), 
				new ChoiceItem("4", "4. Grassland"),
				new ChoiceItem("4.1", "4.1. Grassland - Tundra"), 
				new ChoiceItem("4.2", "4.2. Grassland - Subarctic"), 
				new ChoiceItem("4.3", "4.3. Grassland - Subantarctic"), 
				new ChoiceItem("4.4", "4.4. Grassland - Temperate"), 
				new ChoiceItem("4.5", "4.5. Grassland - Subtropical/Tropical Dry Lowland"),
				new ChoiceItem("4.6", "4.6. Grassland - Subtropical/Tropical Seasonally Wet/Flooded Lowland"),
				new ChoiceItem("4.7", "4.7. Grassland - Subtropical/Tropical High Altitude"),
				new ChoiceItem("5", "5. Wetlands (inland)"),
				new ChoiceItem("5.1", "5.1. Wetlands (inland) - Permanent Rivers/Streams/Creeks [includes waterfalls]"),
				new ChoiceItem("5.2", "5.2. Wetlands (inland) - Seasonal/Intermittent/Irregular Rivers/Streams/Creeks"),
				new ChoiceItem("5.3", "5.3. Wetlands (inland) - Shrub Dominated Wetlands"),
				new ChoiceItem("5.4", "5.4. Wetlands (inland) - Bogs, Marshes, Swamps, Fens, Peatlands"),
				new ChoiceItem("5.5", "5.5. Wetlands (inland) - Permanent Freshwater Lakes [over 8 ha]"),
				new ChoiceItem("5.6", "5.6. Wetlands (inland) - Seasonal/Intermittent Freshwater Lakes [over 8 ha]"),
				new ChoiceItem("5.7", "5.7. Wetlands (inland) - Permanent Freshwater Marshes/Pools [under 8 ha]"),
				new ChoiceItem("5.8", "5.8. Wetlands (inland) - Seasonal/Intermittent Freshwater Marshes/Pools [under 8 ha]"),
				new ChoiceItem("5.9", "5.9. Wetlands (inland) - Freshwater Springs and Oases"),
				new ChoiceItem("5.10", "5.10. Wetlands (inland) - Tundra Wetlands [includes pools and temporary waters from snowmelt]"),
				new ChoiceItem("5.11", "5.11. Wetlands (inland) - Alpine Wetlands [includes temporary waters from snowmelt]"),
				new ChoiceItem("5.12", "5.12. Wetlands (inland) - Geothermal Wetlands"),
				new ChoiceItem("5.13", "5.13. Wetlands (inland) - Permanent Inland Deltas"),
				new ChoiceItem("5.14", "5.14. Wetlands (inland) - Permanent Saline, Brackish or Alkaline Lakes"),
				new ChoiceItem("5.15", "5.15. Wetlands (inland) - Seasonal/Intermittent Saline, Brackish or Alkaline Lakes and Flats"),
				new ChoiceItem("5.16", "5.16. Wetlands (inland) - Permanent Saline, Brackish or Alkaline Marshes/Pools"),
				new ChoiceItem("5.17", "5.17. Wetlands (inland) - Seasonal/Intermittent Saline, Brackish or Alkaline Marshes/Pools"),
				new ChoiceItem("5.18", "5.18. Wetlands (inland) - Karst and Other Subterranean Hydrological Systems [inland]"),
				new ChoiceItem("6", "6. Rocky Areas [e.g. inland cliffs, mountain peaks]"),
				new ChoiceItem("7", "7. Caves and Subterranean Habitats (non-aquatic)"),
				new ChoiceItem("7.1", "7.1. Caves and Subterranean Habitats (non-aquatic) - Caves"),
				new ChoiceItem("7.2", "7.2. Caves and Subterranean Habitats (non-aquatic) - Other Subterranean Habitats"),
				new ChoiceItem("8", "8. Desert"), 
				new ChoiceItem("8.1", "8.1. Desert - Hot"),  
				new ChoiceItem("8.2", "8.2. Desert - Temperate"),
				new ChoiceItem("8.3", "8.3. Desert - Cold"),
				new ChoiceItem("9", "9. Marine Neritic (Submergent Nearshore Continental Shelf or Oceanic Island)"),
				new ChoiceItem("9.1", "9.1. Marine Neritic (Submergent Nearshore Continental Shelf or Oceanic Island) - Pelagic"),
				new ChoiceItem("9.2", "9.2. Marine Neritic (Submergent Nearshore Continental Shelf or Oceanic Island) - Subtidal Rock and Rocky Reefs"),
				new ChoiceItem("9.3", "9.3. Marine Neritic (Submergent Nearshore Continental Shelf or Oceanic Island) - Subtidal Loose Rock/Pebble/Gravel"),
				new ChoiceItem("9.5", "9.5. Marine Neritic (Submergent Nearshore Continental Shelf or Oceanic Island) - Subtidal Sandy"),
				new ChoiceItem("9.6", "9.6. Marine Neritic (Submergent Nearshore Continental Shelf or Oceanic Island) - Subtidal Sandy-Mud"),
				new ChoiceItem("9.7", "9.7. Marine Neritic (Submergent Nearshore Continental Shelf or Oceanic Island) - Macroalgal/Kelp"),
				new ChoiceItem("9.8", "9.8. Coral Reef"),
				new ChoiceItem("9.8.1", "9.8.1. Marine Neritic (Submergent Nearshore Continental Shelf or Oceanic Island) - Coral Reef - Outer Reef Channel"),
				new ChoiceItem("9.8.2", "9.8.2. Marine Neritic (Submergent Nearshore Continental Shelf or Oceanic Island) - Coral Reef - Back Slope"),
				new ChoiceItem("9.8.3", "9.8.3. Marine Neritic (Submergent Nearshore Continental Shelf or Oceanic Island) - Coral Reef - Foreslope (Outer Reef Slope)"),
				new ChoiceItem("9.8.4", "9.8.4. Marine Neritic (Submergent Nearshore Continental Shelf or Oceanic Island) - Coral Reef - Lagoon"),
				new ChoiceItem("9.8.5", "9.8.5. Marine Neritic (Submergent Nearshore Continental Shelf or Oceanic Island) - Coral Reef - Inter-Reef Soft Substrate"),
				new ChoiceItem("9.8.6", "9.8.6. Marine Neritic (Submergent Nearshore Continental Shelf or Oceanic Island) - Coral Reef - Inter-Reef Rubble Substrate"),
				new ChoiceItem("9.9", "9.9. Marine Neritic (Submergent Nearshore Continental Shelf or Oceanic Island) - Seagrass (Submerged)"),
				new ChoiceItem("9.10", "9.10. Marine Neritic (Submergent Nearshore Continental Shelf or Oceanic Island) - Estuaries"),
				new ChoiceItem("10", "10. Marine Oceanic"), 
				new ChoiceItem("10.1", "10.1. Marine Oceanic - Epipelagic (0-200 m)"),
				new ChoiceItem("10.2", "10.2. Marine Oceanic - Mesopelagic (200-1,000 m)"),
				//NOTE: this appears in the jira but has duplicate number
				//new ChoiceItem("10.3", "10.3. Marine Oceanic - Estuarine Waters"),
				new ChoiceItem("10.3", "10.3. Marine Oceanic - Bathypelagic (1,000-4,000 m)"),
				new ChoiceItem("10.4", "10.4. Marine Oceanic - Abyssopelagic (4,000-6,000 m)"),
				new ChoiceItem("11", "11. Marine Deep Benthic"), 
				new ChoiceItem("11.1", "11.1. Marine Deep Benthic - Continental Slope/Bathyl Zone (200-4,000 m)"), 
				new ChoiceItem("11.1.1", "11.1.1. Marine Deep Benthic - Continental Slope/Bathyl Zone (200-4,000 m) - Hard Substrate"), 
				new ChoiceItem("11.1.2", "11.1.2. Marine Deep Benthic - Continental Slope/Bathyl Zone (200-4,000 m) - Soft Substrate"), 
				new ChoiceItem("11.2", "11.2. Marine Deep Benthic - Abyssal Plain (4,000-6,000 m)"), 
				new ChoiceItem("11.3", "11.3. Marine Deep Benthic - Abyssal Mountain/Hills (4,000-6,000 m)"), 
				new ChoiceItem("11.4", "11.4. Marine Deep Benthic - Hadal/Deep Sea Trench (>6,000 m)"), 
				new ChoiceItem("11.5", "11.5. Marine Deep Benthic - Seamount"), 
				new ChoiceItem("11.6", "11.6. Marine Deep Benthic - Deep Sea Vents (Rifts/Seeps)"), 
				new ChoiceItem("12", "12. Marine Intertidal"),
				new ChoiceItem("12.1", "12.1. Marine Intertidal - Rocky Shoreline"), 
				new ChoiceItem("12.2", "12.2. Marine Intertidal - Sandy Shoreline and/or Beaches, Sand Bars, Spits, Etc."), 
				new ChoiceItem("12.3", "12.3. Marine Intertidal - Shingle and/or Pebble Shoreline and/or Beaches"), 
				new ChoiceItem("12.4", "12.4. Marine Intertidal - Mud Flats and Salt Flats"), 
				new ChoiceItem("12.5", "12.5. Marine Intertidal - Salt Marshes (Emergent Grasses)"), 
				new ChoiceItem("12.6", "12.6. Marine Intertidal - Tidepools"), 
				new ChoiceItem("12.7", "12.7. Marine Intertidal - Mangrove Submerged Roots"), 
				new ChoiceItem("13", "13 Marine Coastal/Supratidal"),
				new ChoiceItem("13.1", "13.1. Marine Coastal/Supratidal - Sea Cliffs and Rocky Offshore Islands"), 
				new ChoiceItem("13.2", "13.2. Marine Coastal/Supratidal - Coastal Caves/Karst"), 
				new ChoiceItem("13.3", "13.3. Marine Coastal/Supratidal - Coastal Sand Dunes"), 
				new ChoiceItem("13.4", "13.4. Marine Coastal/Supratidal - Coastal Brackish/Saline Lagoons/Marine Lakes"),
				new ChoiceItem("13.5", "13.5. Marine Coastal/Supratidal - Coastal Freshwater Lakes"), 
				new ChoiceItem("14", "14. Artificial - Terrestrial"),
				new ChoiceItem("14.1", "14.1. Artificial - Terrestrial - Arable Land"),
				new ChoiceItem("14.2", "14.2. Artificial - Terrestrial - Pastureland"), 
				new ChoiceItem("14.3", "14.3. Artificial - Terrestrial - Plantations"), 
				new ChoiceItem("14.4", "14.4. Artificial - Terrestrial - Rural Gardens"), 
				new ChoiceItem("14.5", "14.5. Artificial - Terrestrial - Urban Areas"), 
				new ChoiceItem("14.6", "14.6. Artificial - Terrestrial - Subtropical/Tropical Heavily Degraded Former Forest"), 
				new ChoiceItem("15", "15. Artificial - Aquatic"),
				new ChoiceItem("15.1", "15.1. Artificial - Aquatic - Water Storage Areas (over 8 ha)"), 
				new ChoiceItem("15.2", "15.2. Artificial - Aquatic - Ponds (below 8 ha)"), 
				new ChoiceItem("15.3", "15.3. Artificial - Aquatic - Aquaculture Ponds"), 
				new ChoiceItem("15.4", "15.4. Artificial - Aquatic - Salt Exploitation Sites"), 
				new ChoiceItem("15.5", "15.5. Artificial - Aquatic - Excavations (open)"), 
				new ChoiceItem("15.6", "15.6. Artificial - Aquatic - Wastewater Treatment Areas"), 
				new ChoiceItem("15.7", "15.7. Artificial - Aquatic - Irrigated Land [includes irrigation channels]"), 
				new ChoiceItem("15.8", "15.8. Artificial - Aquatic - Seasonally Flooded Agricultural Land"), 
				new ChoiceItem("15.9", "15.9. Artificial - Aquatic - Canals and Drainage Channels, Ditches"), 
				new ChoiceItem("15.10", "15.10. Artificial - Aquatic - Karst and Other Subterranean Hydrological Systems [human-made]"), 
				new ChoiceItem("15.11", "15.11. Artificial - Aquatic - Marine Anthropogenic Structures"), 
				new ChoiceItem("15.12", "15.12. Artificial - Aquatic - Mariculture Cages"), 
				new ChoiceItem("15.13", "15.13. Artificial - Aquatic - Mari/Brackish-culture Ponds"), 
				new ChoiceItem("16", "16. Introduced Vegetation"),
				new ChoiceItem("17", "17. Other"),
				new ChoiceItem("18", "18. Unknown"),
		};
	}
}
